name: Build for ARM
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Patch
        run: |
            ./patch.sh

      - name: Build
        run: |
            cd upstream \
            && ./BuildLinux.sh -u \
            && ./BuildLinux.sh -dsir \
            && ./BuildLinux.sh -i

      - name: AppImage exists
        run: |
            if [ -f upstream/build/CrealityPrint-*.AppImage ]; then
                echo "AppImage exists"
            else
                echo "AppImage does not exist"
                exit 1
            fi

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            upstream/build/CrealityPrint-*.AppImage
