name: Build for ARM
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Patch
        run: |
            ./patch.sh

      - name: Build
        run: |
            cd upstream \
            && ./BuildLinux.sh -u \
            && ./BuildLinux.sh -dsir

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/*.AppImage
