name: Build for ARM
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Patch
        run: |
            ./patch.sh

      - name: Build
        run: |
            cd upstream \
            && ./BuildLinux.sh -u \
            && ./BuildLinux.sh -dsir

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
            name: AppImage
            path: |
                **/*.AppImage
